name: Build Magisk

on:
  workflow_dispatch:
  repository_dispatch:
    types: [ Source Code Update ]

jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      REPO_URL: https://github.com/topjohnwu/Magisk.git
      REPO_BRANCH: master

    steps:
      - name: Checkout
        uses: actions/checkout@main
    
      - name: Clone source code
        run: |
          git clone --single-branch --depth 1 --recurse-submodules -b $REPO_BRANCH $REPO_URL ${GITHUB_WORKSPACE}/Magisk

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Set up sccache
        uses: hendrikmuhs/ccache-action@main
        with:
          variant: sccache
          key: ${{ runner.os }}-${{ github.sha }}
          restore-keys: ${{ runner.os }}
          max-size: 10000M

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            !~/.gradle/caches/build-cache-*
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Cache build cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches/build-cache-*
          key: ${{ runner.os }}-build-cache-${{ github.sha }}
          restore-keys: ${{ runner.os }}-build-cache-

      - name: Set up NDK
        run: |
          cd ${GITHUB_WORKSPACE}/Magisk
          python build.py -v ndk

      - name: Build App
        id: compile
        run: |
          cd ${GITHUB_WORKSPACE}/Magisk
          python build.py -vr all
          python build.py -v all
          echo "status=success" >> "$GITHUB_OUTPUT"

      - name: Stop gradle daemon
        run: |
          cd ${GITHUB_WORKSPACE}/Magisk
          ./gradlew --stop

      - name: Sign APK
        if: steps.compile.outputs.status == 'success'
        run: |
          cd ${GITHUB_WORKSPACE}
          chmod +x ./SDK/zipalign
          apks=$(find ${GITHUB_WORKSPACE}/Magisk/out -name '*.apk')
          for apk in $apks
          do
            ./SDK/zipalign -v 4 $apk $apk.signed
            rm -rf $apk
            java -jar signapk.jar Magisk.x509.pem Magisk.pk8 $apk.signed $apk
            rm -rf $apk.signed
          done

      - name: Generate tag
        id: tag
        if: steps.compile.outputs.status == 'success'
        run: |
          cd ${GITHUB_WORKSPACE}/Magisk
          echo "release_tag=$(git rev-parse HEAD | cut -c 1-8)" >> "$GITHUB_OUTPUT"
          echo "release_body=$(grep "magisk.versionCode" gradle.properties | awk -F "=" '{print $2}')-$(grep "magisk.stubVersion" gradle.properties | awk -F "=" '{print $2}')" >> "$GITHUB_OUTPUT"
          echo "status=success" >> "$GITHUB_OUTPUT"

      - name: Make Notes
        if: steps.tag.outputs.status == 'success'
        run: |
          cd ${GITHUB_WORKSPACE}/Magisk
          ver=$(echo ${{ steps.tag.outputs.release_body }} | awk -F "-" '{print $1}')
          echo "## Magisk (${{ steps.tag.outputs.release_tag }}) (${ver})" > ./out/notes.md
          json=$(curl -sL -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/repos/topjohnwu/Magisk/commits | jq .)
          jsha=$(echo $json | jq .[].sha | sed 's/\"//g')
          hsha=$(curl -sL -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/repos/hubbylei/Magisk-Files/commits | jq .[0].commit.message | sed 's/\"//g' | awk -F "-" '{print $1}')
          sha=()
          i=0
          for s in $jsha
          do
            sha[$i]=$(echo $s | cut -c 1-8)
            i=$(($i+1))
          done
          for ((i=0;i <${#sha[@]};i++))
          do
            if [ ${sha[$i]} == $hsha ];then
                break
            fi
            echo "- "$(echo $json | jq .[$i].commit.message | sed 's/\\n/<br>/g' | sed 's/\"//g') >> ./out/notes.md
          done

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        if: steps.tag.outputs.status == 'success' && !cancelled()
        with:
          name: ${{ steps.tag.outputs.release_tag }}(${{ steps.tag.outputs.release_body }})
          path: ${GITHUB_WORKSPACE}/Magisk/out

      - name: Upload To File Host
        uses: hubbylei/github-action-push-to-another-repository@main
        if: steps.tag.outputs.status == 'success'
        env:
          API_TOKEN_GITHUB: ${{ secrets.MAGISK_BUILD_CHECK }}
        with:
          source-directory: '${GITHUB_WORKSPACE}/Magisk/out'
          destination-github-username: 'hubbylei'
          destination-repository-name: 'Magisk-Files'
          user-email: ${{ secrets.UESR_EMAIL }}
          commit-message: ${{ steps.tag.outputs.release_tag }}-${{ steps.tag.outputs.release_body }}
          target-branch: master

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 0
          keep_minimum_runs: 1
