name: Build Magisk
on:
  workflow_dispatch:
  repository_dispatch:
    types: [ Build_Magisk ]

env:
  REPO_URL: https://github.com/topjohnwu/Magisk.git
  REPO_BRANCH: master
  SCCACHE_DIRECT: false
jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@main
    
      - name: Clone source code
        id: clone
        run: |
          git clone --single-branch --depth 1 --recurse-submodules -b $REPO_BRANCH $REPO_URL Magisk
          cd Magisk
          echo "Hash=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"

      - name: Setup environment
        uses: ./.github/actions/setup
        with:
          is-asset-build: true

      - name: Build Release
        id: release
        run: |
          cd Magisk
          python build.py -vr all
          echo "status=success" >> "$GITHUB_OUTPUT"

      - name: Build Debug
        id: debug
        run: |
          cd Magisk
          python build.py -v all
          echo "status=success" >> "$GITHUB_OUTPUT"

      - name: Stop gradle daemon
        run: |
          cd Magisk
          ./app/gradlew --stop

      - name: Sign APK
        if: steps.release.outputs.status == 'success' && steps.debug.outputs.status == 'success'
        run: |
          chmod a+x ./signer/zipalign
          chmod a+x ./signer/apksigner
          apks=$(find Magisk/out -name '*.apk')
          for apk in $apks
          do
            echo "Sign $apk"
            ./signer/zipalign -v 4 $apk $apk.signed > /dev/null
            rm -rf $apk
            mv $apk.signed $apk
            ./signer/apksigner sign --cert Magisk.x509.pem --key Magisk.pk8 $apk
            rm -rf $apk.idsig
          done

      - name: Generate tag
        id: tag
        if: steps.release.outputs.status == 'success' && steps.debug.outputs.status == 'success'
        run: |
          cd Magisk
          echo "release_tag=$(git rev-parse HEAD | cut -c 1-8)" >> "$GITHUB_OUTPUT"
          echo "release_version=$(grep "magisk.versionCode" app/gradle.properties | awk -F "=" '{print $2}')-$(grep "magisk.stubVersion" app/gradle.properties | awk -F "=" '{print $2}')" >> "$GITHUB_OUTPUT"
          echo "status=success" >> "$GITHUB_OUTPUT"

      - name: Make Notes
        if: steps.tag.outputs.status == 'success'
        run: bash Notes.sh Magisk

      - name: Upload Artifact
        if: steps.tag.outputs.status == 'success' && !cancelled()
        uses: actions/upload-artifact@main
        with:
          name: ${{ steps.tag.outputs.release_tag }}(${{ steps.tag.outputs.release_version }})
          path: Magisk/out
          compression-level: 9

      - name: Generate HEAD
        run: echo ${{ steps.clone.outputs.Hash }} > Magisk/out/HEAD

      - name: Upload To File Host
        if: steps.tag.outputs.status == 'success'
        uses: hubbylei/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.MAGISK_BUILD_CHECK }}
        with:
          source-directory: 'Magisk/out'
          destination-github-username: 'hubbylei'
          destination-repository-name: 'Magisk-Files'
          user-email: ${{ secrets.UESR_EMAIL }}
          commit-message: ${{ steps.tag.outputs.release_tag }}-${{ steps.tag.outputs.release_version }}
          target-branch: master

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 0
          keep_minimum_runs: 3
