name: Build Magisk

on:
  workflow_dispatch:
  repository_dispatch:
    types: [ Source Code Update ]

jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      REPO_URL: https://github.com/topjohnwu/Magisk
      REPO_BRANCH: master
      NDK_CCACHE: ccache
      CCACHE_DIR: ${{ github.workspace }}/.ccache
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      RUSTC_WRAPPER: sccache

    steps:
      - name: Clone source code
        run: |
          df -hT $PWD
          git clone --recurse-submodules $REPO_URL -b $REPO_BRANCH ./

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Set up ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ runner.os }}-${{ github.sha }}
          restore-keys: ${{ runner.os }}

      - name: Set up sccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          variant: sccache
          key: ${{ runner.os }}-${{ github.sha }}
          restore-keys: ${{ runner.os }}

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            !~/.gradle/caches/build-cache-*
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Cache build cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches/build-cache-*
          key: ${{ runner.os }}-build-cache-${{ github.sha }}
          restore-keys: ${{ runner.os }}-build-cache-

      - name: Set up NDK
        run: python build.py -v ndk

      - name: Build App
        id: compile
        run: |
          python build.py -vr all
          python build.py -v all
          echo "::set-output name=status::success"

      - name: Stop gradle daemon
        run: ./gradlew --stop

      - name: Generate tag
        id: tag
        if: steps.compile.outputs.status == 'success'
        run: |
          echo "::set-output name=release_tag::$(git rev-parse HEAD | cut -c 1-8)"
          echo "::set-output name=release_body::$(grep "magisk.versionCode" gradle.properties | awk -F "=" '{print $2}')-$(grep "magisk.stubVersion" gradle.properties | awk -F "=" '{print $2}')"
          echo "::set-output name=status::success"

      - name: Upload firmware to release
        uses: softprops/action-gh-release@v1
        if: steps.tag.outputs.status == 'success' && !cancelled()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          body: ${{ steps.tag.outputs.release_tag }} - ${{ steps.tag.outputs.release_body }}
          files: out/*

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 0
          keep_minimum_runs: 1
          
