name: Update Checker

env:
  REPO_URL: https://github.com/topjohnwu/Magisk
  REPO_BRANCH: master

on:
  workflow_dispatch:
  schedule:
    - cron: 0 17 * * *

jobs:
  check:
    runs-on: ubuntu-latest

    steps:

    - name: Get Commit Hash
      id: getHash
      run: |
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH .
        echo "commitHash=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"

    - name: Restore Commit Hash
      id: cacheHash
      uses: actions/cache@main
      with:
        path: commitHash
        key: HEAD-${{ github.sha }}
        restore-keys: HEAD-

    - name: Compare Commit Hash
      id: save
      run: |
        if [ -d commitHash ];then
          cacheVer=$(ls commitHash)
        fi
        getVer=${{ steps.getHash.outputs.commitHash }}
        echo "CacheVer: ${cacheVer}"
        echo "getVer: ${getVer}"
        if [ "${cacheVer}" == "${getVer}" ];then
          echo "build=false" >> "$GITHUB_OUTPUT"
        else
          rm -rf commitHash
          mkdir -p commitHash
          echo ${getVer} > commitHash/${getVer}
          echo "build=true" >> "$GITHUB_OUTPUT"
        fi

    - name: Build
      if: steps.save.outputs.build == 'true'
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ secrets.MAGISK_BUILD_CHECK }}
        event-type: Build_Magisk

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 0
        keep_minimum_runs: 3
